### ISSUE TITLE
Live full screen video - question and comment 

### ISSUE THREAD

**Issue by Michael-Axelsson** [Billwilliams1952/PiCameraApp#5]
Hi

I am completely new to Rasberry pi and programming in anything else than Labview. I am coordinating a microsurgery training center in Gothenburg (http://microsurgery.se/) and are looking at simple and cheap ways to monitor the work by the participants when they work. 
I have tried very expensive solutions like side tubes (5000 EUR), Leica microscope camera system for around 3500 EUR. I also used modified Logitech c920 cameras (mounted in a new house with a c-mount) in combination with Samsung tablet and the CameraFi app, that combination is around 600 EUR so cheapest so far, I can view live full screen (10" screen) sae images or video and also cast (Chrome cast) the live feed to the teaching screen in the front of the room. BUT there is an issue with simultaneous charging the tablet and viewing the camera since they use the same USB port.

Read about the Rasberry pi system and the camera that together is very cheap, combined with a 10" touch screen it would make e even cheaper system and without the problem with simultaneous charging

My problem is that I do not now how to create a program for this, I would like to have a program that can do all the things that your program is doing (control of the camera, save still images and live video) but also show a full screen live video feed from the microscope but I cannot see this possibility

A comment
My Rasberry is runnig Python 2.7.9 (pyhton --version) so I should start your program with the command sudo "python PiCameraApp.py" that does not work but "sudo python3 PiCameraApp.py" works (tried this in desperation after reading all the instruction and installing all the things needed

Sincerely
Michael Axelsson

**Comment by Billwilliams1952** [comment]
Hi Michael,

I’d be glad to help but I would need more info on your system. The live feed that you mention - what is it, the interface (USB?), the hardware. There may be a way to get this feed on an RPI running Linux  - possibly using VLC. Similar to opening a video feed from a webcam. 

I can look at integrating a webcam interface into my PiCamera app. 

Let me know if that could be useful. I don’t know if it’s the best solution but I can at least look at it. 

Good luck and keep me in touch!

Bill

**Comment by Michael-Axelsson** [comment]
Hi Bill

First of all, thank you for replaying
I am new to github, and programing but have an idea that I would like to test in the hope that it will be a stable, and cheaper solution (than what I have) to a problem in microsurgery training.

I would like to test the raspberry pi 3 in combination with a  Rasberry camera module 2. I have the Rasberry pi 3 attached on the back of a 10” touch screen (SunFounder)
(see attached picture). I will 3D print a back for the screen/Rasberry pi so that it can be mounted on an adjustable arm down in the microsurgery lab. The Camera module 2 is mounted in a 3D printed adapter (grey tube in the attached picture) for a sidetube to one of the microscopes but I will also try the camera in a ocular adapter later on but need a c-mount adapter that I have not yet printed/manufactured

What I would like to do is to see a full screen live video on the 10” screen, no streaming or web-interface just the feed from the camera on the screen and I woul like to be able to save e still images and video for documentation and also to adjust the camera settings (basic settings like brightness, saturation, contrast ..)
I attach a Powerpoint with two slides that describes what I had in mind

I downloaded and “installed” the PiCameraApp and everything is there (and much more) except the full screen view, the Overlay size adjust the live feed but I cannot get it to show full screen which is 650x410 on the screen that I use.

If it would be possible to use USB camera instead of the Camera module 2 that would be a bonus but I think that the camera module 2 will do the job and it is cheaper than the Logitech c920 or 525 cameras I have used in combination with the Samsung Galaxy 10” units

Sincerely
Michael Axelsson

**Comment by Billwilliams1952** [comment]
Hi Michael,

You have a great design going! I will be glad to update the code to give you full screen capability.

I am on a short vacation with the wife in New Orleans and will be back home on Friday. You should be able to download an updated version by Monday. 

If you need anything else - let me know. 

Ps, If you ever publish your results I’d love to get a copy (assuming it’s allowed). 

Bill

**Comment by Michael-Axelsson** [comment]
Hi Bill

Thank you so much
I attended a conference in New Orelans a couple of years ago and we (my wife and I) enjoyed city the surroundings even you still (and probably for a long time to come) could see the effects of Katrina

I will keep in contact with you since I think that I will have questions and I intend to present the results of my quest for reliable and affordable viewing station for microsurgery training at the upcoming International Society for Experimental Microsurgery in Hungary in August (http://www.isem2018.org/). I will of cause acknowledged everybody that have helped me  with my project

We do occasionally publish papers from our training center and collaborations, I attach the two we published so far and of causr if iór rather when we publish the results from another project called micro-TRACK and the micro-VIEW (which is my working name for the viewing project we will again acknowledge you and other contributors and send you reprints

Sincerely
Michael Axelsson



Från: Bill Williams [mailto:notifications@github.com]
Skickat: den 14 mars 2018 18:19
Till: Billwilliams1952/PiCameraApp
Kopia: Michael Axelsson; Author
Ämne: Re: [Billwilliams1952/PiCameraApp] Live full screen video - question and comment (#5)

Hi Michael,

You have a great design going! I will be glad to update the code to give you full screen capability.

I am on a short vacation with the wife in New Orleans and will be back home on Friday. You should be able to download an updated version by Monday.

If you need anything else - let me know.

Ps, If you ever publish your results I’d love to get a copy (assuming it’s allowed).

Bill

**Comment by Billwilliams1952** [comment]
New Orleans is a great city to visit!

For full screen overlay, you’ll need some on screen ‘buttons’ to control the app, since you can’t see the app anymore - unless you turn the transparency up (not recommended). I’ll try to prototype a simple button overlay (‘close’, ‘take video’, ‘take picture’, ...., etc).  Let me know if you specific requirements. 

Ps, I didn’t get any picture or file attachments. If you wish, you can send me emails at billwilliams2718@gmail.com. 

Bill

**Comment by Michael-Axelsson** [comment]
Hi

Ok, I try sending the attachments to the gmail, most likely screen out

Cheers
Michael

Från: Bill Williams [mailto:notifications@github.com]
Skickat: den 14 mars 2018 21:45
Till: Billwilliams1952/PiCameraApp
Kopia: Michael Axelsson; Author
Ämne: Re: [Billwilliams1952/PiCameraApp] Live full screen video - question and comment (#5)

New Orleans is a great city to visit!

For full screen overlay, you’ll need some on screen ‘buttons’ to control the app, since you can’t see the app anymore - unless you turn the transparency up (not recommended). I’ll try to prototype a simple button overlay (‘close’, ‘take video’, ‘take picture’, ...., etc). Let me know if you specific requirements.

Ps, I didn’t get any picture or file attachments. If you wish, you can send me emails at billwilliams2718@gmail.com<mailto:billwilliams2718@gmail.com>.

Bill

**Comment by Billwilliams1952** [comment]
Thanks!

**Comment by Michael-Axelsson** [comment]
Hi

Please let me know if you get gmail with the image and PDF
In the PDF I have indicated what you describes the overlay buttons to save images, save video, get into the setting and terminate the program
The mage just shows the pi camera and first 3D printed adapter

Sincerely
Michael

Från: Bill Williams [mailto:notifications@github.com]
Skickat: den 14 mars 2018 21:48
Till: Billwilliams1952/PiCameraApp
Kopia: Michael Axelsson; Author
Ämne: Re: [Billwilliams1952/PiCameraApp] Live full screen video - question and comment (#5)

Thanks!

**Comment by Michael-Axelsson** [comment]
Hi again

Reading the log in github I realize that I should not include the previous text if I am using Outlook to reply, it get to long, sorry about that

I include the two files that I tried to send 

Sincerely
Michael
![20180314_100711](https://user-images.githubusercontent.com/36626898/37519259-b4bec74e-2918-11e8-9689-22ac2f96c537.jpg)
[micro-VIEW.pdf](https://github.com/Billwilliams1952/PiCameraApp/files/1819053/micro-VIEW.pdf)
